### ISSUE TITLE
old VoSeq paper repository

### ISSUE THREAD

**Issue by abubelinha** [carlosp420/voseq2-ms#1]
@carlosp420 I'm trying to find the VoSeq repository cited here:

> ### [VoSeq: A Voucher and DNA Sequence Web Application](https://www.researchgate.net/publication/225303161_VoSeq_a_Voucher_and_DNA_Sequence_web_application)
> Carlos Peña & Tobias Malm 
> June 2012 PLoS ONE 7(6):e39071
>  https://doi.org/10.1371/journal.pone.0039071
> 
> **Availability and future directions**
> The software is open source with a GPL v2 license: https://github.com/carlosp420/VoSeq. A test installation with sample data can be found at http://www.nymphalidae.net/VoSeq. The full documentation and how-to help can be accessed here: http://nymphalidae.utu.fi/cpena/VoSeq_docu.html.
> 

But none of those links work.
As your github user accounts exists, could you please reupload the github carlosp420/VoSeq repository?

Thanks
@abubelinha

**Comment by carlosp420** [comment]
Hi,
I just created an invite for you to the repository
https://github.com/VoSeq/VoSeq/

carlos

**Comment by abubelinha** [comment]
Thanks @carlosp420 
First time I hear about invitations.
Does this mean the project is not opensource?
